# Generated by Django 3.2.4 on 2021-09-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('TagId', models.AutoField(primary_key=True, serialize=False)),
                ('Start', models.IntegerField()),
                ('Start_span_id', models.IntegerField()),
                ('Txxt', models.TextField()),
                ('End', models.IntegerField()),
                ('End_span_id', models.IntegerField()),
                ('Label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('TextId', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
            ],
        ),
    ]
